### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by qzq-hit** [yanlongbinluck/HSI-Object-Detection-NPU#1]
Dear Yan, I have just read your article ——"Object Detection in Hyperspectral Images," in IEEE Signal Processing Letters, vol. 28, pp. 508-512, 2021, doi: 10.1109/LSP.2021.3059204. You have made a great contribution to the field of hyperspectrum that you created a hyperspectral dataset for object-level target detection. But I didn't find the download link, which doesn't match what you said in your article. Could you please give me the download link of the dataset? I will quote your article if I use it. Thanks sincerely.

**Comment by yanlongbinluck** [comment]
Thanks for your attention for our work. It will be soon. Maybe about 2-3 days.

**Comment by yanlongbinluck** [comment]
Hi, the link of dataset has been added.

**Comment by qzq-hit** [comment]
I'm sorry. I can't download the dataset with the password 'y4mp'.The password is wrong. Could you please figure it out for me?

**Comment by yanlongbinluck** [comment]
Sorry for the inconvenience. It was our negligence that caused this problem, and I have modified the link.

**Comment by bach05** [comment]
Hi, 

for me it is near impossible to use Baidu Cloud. Can I kindly ask if it is possible to upload the same dataset on another cloud like [Mega](https://mega.nz/) or whatever else? 

Thank you in advance.

**Comment by yanlongbinluck** [comment]
@bach05 ,Hi, I have uploaded the 96-channel data to Onedrive. Please see README file.
