### ISSUE TITLE
the download link about the pretrained model

### ISSUE THREAD

**Issue by TimZhang001** [yanlongbinluck/HSI-Object-Detection-NPU#2]
Hi,

Thanks about the dataset and the object detection pipeline of HSI。

But i cannot get the passwords of the link of the pretrained model.

our pretrained model: [baidu cloud](https://pan.baidu.com/s/11mQsR10Z35EH6Kw9__LyrA)

Also, it is mentioned that, An RGB dataset with 2084 images is also provided. But i cannot find any RGB data.

**Comment by yanlongbinluck** [comment]
Hi, Thanks for your attention for our work.
1. the missed password for pretrained model is added.
2. the RGB dataset is uploaded， please see  RGB_image_data.zip for details. Please note that the control experiments to compare the detection performance for RGB and HSI should be conducted with the same numbers of images.

**Comment by TimZhang001** [comment]
> Hi, Thanks for your attention for our work.
> 
> 1. the missed password for pretrained model is added.
> 2. the RGB dataset is uploaded， please see  RGB_image_data.zip for details. Please note that the control experiments to compare the detection performance for RGB and HSI should be conducted with the same numbers of images.


It's appreciate for your quick reply, and it helps me a lot. 
Also, it's mentioned that Note that "more technical details, experimental settings and results can be found in the supplemental full-length report", but I cannot find the supplemental report from everywhere.

**Comment by yanlongbinluck** [comment]
here，https://ieeexplore.ieee.org/ielx7/97/9325893/9354961/supp1-3059204.pdf?arnumber=9354961
it is in “Media” section.
